[package]
name = "yace-codegen"
version = "0.0.1"
authors = ["Igor Pavlychev <zdemia@mail.ru>"]
description = "Procedural macros for 𝔜𝔄ℭ𝔈."
license = "MIT"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
